---
apiVersion: v1
kind: Service
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    name: client
  selector:
    app: middleware
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
      annotations:
        df.k8-app.name: "Eureka"
        df.k8-app.registration/inject: "enabled"
        df-k8-app.alert/policy: "Default Policy: Max Alert"
        app-image/repo-details: "johnkday/fioapp:latest"
        df.k8-app.run.token/runtoken: "<your token here>"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - middleware
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: middleware
          image: "johnkday/fioapp:latest"
          imagePullPolicy: Always
          env:
            - name: LD_PRELOAD
              value: /opt/deepfactor/lib/libdf.so
            - name: DF_MANIFEST
              value: /opt/deepfactor/manifest/df-manifest.json
